apiVersion: v1
kind: Service
metadata:
  name: ipl-frontend-service
  labels:
    app: ipl-frontend-service
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 3000
      protocol: TCP
      name: http
      nodePort: 30001
  selector:
    app: ipl-frontend-deployment
