apiVersion: v1
kind: Service
metadata:
  name: {{ include "ipl-backend-helm.fullname" . }}
  labels:
    {{- include "ipl-backend-helm.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
      nodePort: 30000
  selector:
    {{- include "ipl-backend-helm.selectorLabels" . | nindent 4 }}
