apiVersion: v1
kind: Service
metadata:
  name: ipl-backend-service
  labels:
    app: ipl-backend-service
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
      nodePort: 30000
  selector:
    app: ipl-backend-deployment
